### ISSUE TITLE
cannot see full paths to conda envs

### ISSUE THREAD

**Issue by nick-youngblut** [mamba-org/gator#43]
## Description

For conda envs installed in custom locations, the path can be too long to fully display in the launcher (see the attached pic). In my case, many of the conda env "tiles" in the launcher look exactly the same. It would be nice if the user could change the format to just a list of paths instead of the default "tile" view. 

<img width="827" alt="Screen Shot 2020-05-23 at 9 33 20 PM" src="https://user-images.githubusercontent.com/2468572/82739540-9dda0400-9d40-11ea-8d7f-60ec52f3b13b.png">

## Context

- Operating System and version:
- Browser and version: Chrome 81.0.4044.138
- JupyterLab version: 2.1.3-py_0
- jupyterlab_conda version: up-to-date

**Comment by fcollonval** [comment]
Hey @nick-youngblut thank you for reaching out.

That problem is not related to this package directly. Indeed, the conda environment are made available as kernel thanks to [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels). Then the default JupyterLab launcher is building all those cards.

There have been discussion and some propositions to improve that Launcher. But so far none of it made it to the code (see [#3795](https://github.com/jupyterlab/jupyterlab/issues/3795) or [#5953](https://github.com/jupyterlab/jupyterlab/pull/5953)).

One trick enabled by `nb_conda_kernels` is to modify the default name. It could help you: see https://github.com/jupyterlab/jupyterlab/issues/3795#issuecomment-455669749

**Comment by nick-youngblut** [comment]
I haven't yet switched from Jupyter to Jupyter Lab, mainly due to this issue. I assumed that a simple fix would be implemented by now (eg., hovering over the icons would show the entire conda env name instead of just the truncated versions), but I guess the user still either has to "click and pray" with the hope they got the right conda env, or hack the naming as is proposed by @fcollonval (thanks for the suggestion! but it's not a straight forward way of solving what should be a minor UI issue).

**Comment by nick-youngblut** [comment]
Even with truncating the names (via `jupyter lab --CondaKernelSpecManager.name_format="'{1}'"`; see https://github.com/jupyterlab/jupyterlab/issues/3795#issuecomment-463743040), I still can tell some conda envs apart from one another (see pic). I'm surprised that no one has simply provided an option for a simple list instead of tiles (buttons). btw, I'm using Jupyter Lab 2.2.8

<img width="855" alt="Screen Shot 2020-10-08 at 8 43 08 PM" src="https://user-images.githubusercontent.com/2468572/95500282-e4a26080-09a6-11eb-8dae-d8ccb00f53f1.png">

**Comment by fcollonval** [comment]
There is now an alternative launcher with list view to address this issue:
https://github.com/fcollonval/jlab-enhanced-launcher

Moreover the `name_format` configuration of `nb_conda_kernels` has been extended to support more customization (starting from v2.3.1):
https://github.com/Anaconda-Platform/nb_conda_kernels#configuration
